Update setup script

diff --git a/docker/start-container b/docker/start-container
--- a/docker/start-container
+++ b/docker/start-container
@@ -1,16 +1,34 @@
 #!/usr/bin/env bash
 
+# Load environment variables from .env file
+if [ -f .env ]; then
+    export $(grep -v '^#' .env | xargs)
+else
+    echo ".env file not found"
+    exit 1
+fi
+
+check_mysql() {
+    echo "Checking MySQL readiness..."
+    until mysql -h"$DB_HOST" -u"$DB_USERNAME" -p"$DB_PASSWORD" -e "SELECT 1;" > /dev/null 2>&1; do
+        echo "Waiting for MySQL to be ready..."
+        sleep 5
+    done
+    echo "Success: MySQL is up and running."
+}
+
+check_mysql
+
 chmod -R 777 /var/www/html/storage
 chmod -R 777 /var/www/html/bootstrap/cache
 composer install
-#php artisan config:cache
+
 php artisan key:generate
 php artisan optimize
 php artisan migrate --force
-# php artisan migrate:fresh --force
-# php artisan db:seed
-npm i
-npm run build
+
+#npm i
+#npm run build
 
 if [ ! -z "$WWWUSER" ]; then
     usermod -u $WWWUSER sail
@@ -31,3 +49,4 @@ else
         exec /usr/bin/supervisord -c /etc/supervisor/conf.d/webserver.conf
     fi
 fi
+
